# version: '3.1'
# services:
#   server:
#     image: akashmondal0/skylight-backend:latest
#     restart: always
#     ports:
#       - 4000:4000
#     environment:
#       KAFKA_BROKER: "<local ip address>:9092"
#       # for kafka ssl
#       CA_PATH: "./src/kafka/ca.pem"
#       SASL_MECHANISM: ""
#       SASL_USERNAME: ""
#       SASL_PASSWORD: ""

  # client:
  #   image: akashmondal0/skylight:latest
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NEXT_PUBLIC_HOST_URL: "http://localhost:4000"
  
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 60 1
  #   volumes:
  #     - ./rdata:/rdata
  #     - ./docker_datas/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     REDIS_PASSWORD: akash1234
  #     REDIS_PORT: 6379
  #     REDIS_DATABASES: 1
  
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 2181:2181
  #   environment:
  #     # kafka docker image env
  #     KAFKA_ZOOKEEPER_CONNECT: <local ip address>:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<local ip address>:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     # kafka broker env
  #     KAFKA_BROKER: <local ip address>:9092
    
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9092:9092
  #     - 29092:29092
  #   environment:
  #     # kafka docker image env
  #     KAFKA_ZOOKEEPER_CONNECT: <local ip address>:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<local ip address>:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     # kafka broker env
  #     KAFKA_BROKER: <local ip address>:9092

  # prometheus-server:
  #   image: prom/prometheus
  #   restart: always
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  # grafana:
  #   image: grafana/grafana-oss:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"

  # grafana-loki:
  #   image: grafana/loki:latest
  #   restart: always
  #   ports:
  #     - "3100:3100"